In [1]:
!pip install osmnx folium

Requirement already satisfied: osmnx in ./venv/lib/python3.10/site-packages (2.0.7)
Requirement already satisfied: folium in ./venv/lib/python3.10/site-packages (0.20.0)
Requirement already satisfied: requests>=2.27 in ./venv/lib/python3.10/site-packages (from osmnx) (2.33.1)
Requirement already satisfied: geopandas>=1.0.1 in ./venv/lib/python3.10/site-packages (from osmnx) (1.1.3)
Requirement already satisfied: shapely>=2.0 in ./venv/lib/python3.10/site-packages (from osmnx) (2.1.2)
Requirement already satisfied: networkx>=2.5 in ./venv/lib/python3.10/site-packages (from osmnx) (3.4.2)
Requirement already satisfied: numpy>=1.22 in ./venv/lib/python3.10/site-packages (from osmnx) (2.2.6)
Requirement already satisfied: pandas>=1.4 in ./venv/lib/python3.10/site-packages (from osmnx) (2.3.3)
Requirement already satisfied: jinja2>=2.9 in ./venv/lib/python3.10/site-packages (from folium) (3.1.6)
Requirement already satisfied: branca>=0.6.0 in ./venv/lib/python3.10/site-packages (from folium) (0.8.2)
Requirement already satisfied: xyzservices in ./venv/lib/python3.10/site-packages (from folium) (2026.3.0)
Requirement already satisfied: pyogrio>=0.7.2 in ./venv/lib/python3.10/site-packages (from geopandas>=1.0.1->osmnx) (0.12.1)
Requirement already satisfied: packaging in ./venv/lib/python3.10/site-packages (from geopandas>=1.0.1->osmnx) (26.0)
Requirement already satisfied: pyproj>=3.5.0 in ./venv/lib/python3.10/site-packages (from geopandas>=1.0.1->osmnx) (3.7.1)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.10/site-packages (from jinja2>=2.9->folium) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.10/site-packages (from pandas>=1.4->osmnx) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./venv/lib/python3.10/site-packages (from pandas>=1.4->osmnx) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in ./venv/lib/python3.10/site-packages (from pandas>=1.4->osmnx) (2026.1)
Requirement already satisfied: certifi in ./venv/lib/python3.10/site-packages (from pyogrio>=0.7.2->geopandas>=1.0.1->osmnx) (2026.2.25)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas>=1.4->osmnx) (1.17.0)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.10/site-packages (from requests>=2.27->osmnx) (3.11)
Requirement already satisfied: charset_normalizer<4,>=2 in ./venv/lib/python3.10/site-packages (from requests>=2.27->osmnx) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in ./venv/lib/python3.10/site-packages (from requests>=2.27->osmnx) (2.6.3)
WARNING: You are using pip version 21.2.3; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/dikshanta/Documents/Intelligent_Agents/venv/bin/python3 -m pip install --upgrade pip' command.

In [2]:
import osmnx as ox
G = ox.graph_from_xml("/Users/dikshanta/Documents/Intelligent_Agents/task.osm")

In [3]:
list(G.nodes())[:5]

[8289423392, 9594032161, 9594032162, 9594032163, 9594032164]

In [4]:
G.nodes[8289423392]

{'y': 28.2235646, 'x': 83.6743721}

In [5]:
G.edges

OutMultiEdgeView([(8289423392, 9594032161, 0), (8289423392, 9594032161, 1), (8289423392, 8289423680, 0), (8289423392, 8289423712, 0), (9594032161, 8289423392, 0), (9594032161, 8289423392, 1), (9594032161, 9594032162, 0), (9594032161, 9594032162, 1), (9594032162, 9594032161, 0), (9594032162, 9594032161, 1), (9594032162, 9594032163, 0), (9594032162, 9594032163, 1), (9594032163, 9594032162, 0), (9594032163, 9594032162, 1), (9594032163, 9594032164, 0), (9594032163, 9594032164, 1), (9594032164, 9594032163, 0), (9594032164, 9594032163, 1), (9594032164, 9594032165, 0), (9594032164, 9594032165, 1), (9594032165, 9594032164, 0), (9594032165, 9594032164, 1), (9594032165, 9594032166, 0), (9594032165, 9594032166, 1), (9594032166, 9594032165, 0), (9594032166, 9594032165, 1), (9594032166, 9594032167, 0), (9594032166, 9594032167, 1), (9594032167, 9594032166, 0), (9594032167, 9594032166, 1), (9594032167, 9594032168, 0), (9594032167, 9594032168, 1), (9594032168, 9594032167, 0), (9594032168, 9594032167, 1), (9594032168, 9594032169, 0), (9594032168, 9594032169, 1), (9594032169, 9594032168, 0), (9594032169, 9594032168, 1), (9594032169, 9594032170, 0), (9594032169, 9594032170, 1), (9594032170, 9594032169, 0), (9594032170, 9594032169, 1), (9594032170, 9594032171, 0), (9594032170, 9594032171, 1), (9594032173, 9594032172, 0), (9594032173, 9594032172, 1), (9594032173, 8289423704, 0), (9594032173, 8289423704, 1), (9594032172, 9594032171, 0), (9594032172, 9594032171, 1), (9594032172, 9594032173, 0), (9594032172, 9594032173, 1), (9594032171, 9594032170, 0), (9594032171, 9594032170, 1), (9594032171, 9594032172, 0), (9594032171, 9594032172, 1), (11840443527, 11840443526, 0), (11840443527, 11840443526, 1), (11840443527, 3739546538, 0), (11840443527, 3739546538, 1), (11840443526, 3600917412, 0), (11840443526, 3600917412, 1), (11840443526, 11840443527, 0), (11840443526, 11840443527, 1), (11840443525, 8289423686, 0), (11840443525, 8289423686, 1), (11840443525, 3600917412, 0), (11840443525, 3600917412, 1), (9598794475, 8289423690, 0), (9598794475, 8289423690, 1), (9598794475, 8289423689, 0), (9598794475, 8289423689, 1), (8289423680, 8289423681, 0), (8289423680, 8289423681, 1), (8289423680, 8289423392, 0), (8289423680, 8289423712, 0), (8289423681, 8289423682, 0), (8289423681, 8289423682, 1), (8289423681, 8289423680, 0), (8289423681, 8289423680, 1), (8289423682, 3739546538, 0), (8289423682, 3739546538, 1), (8289423682, 8289423681, 0), (8289423682, 8289423681, 1), (8289423686, 8289423687, 0), (8289423686, 8289423687, 1), (8289423686, 11840443525, 0), (8289423686, 11840443525, 1), (8289423687, 8289423688, 0), (8289423687, 8289423688, 1), (8289423687, 8289423686, 0), (8289423687, 8289423686, 1), (8289423688, 8289423689, 0), (8289423688, 8289423689, 1), (8289423688, 8289423687, 0), (8289423688, 8289423687, 1), (8289423689, 9598794475, 0), (8289423689, 9598794475, 1), (8289423689, 8289423688, 0), (8289423689, 8289423688, 1), (8289423690, 8289423691, 0), (8289423690, 8289423691, 1), (8289423690, 9598794475, 0), (8289423690, 9598794475, 1), (8289423691, 8289423694, 0), (8289423691, 8289423694, 1), (8289423691, 8289423690, 0), (8289423691, 8289423690, 1), (8289423694, 8289423695, 0), (8289423694, 8289423695, 1), (8289423694, 8289423691, 0), (8289423694, 8289423691, 1), (8289423695, 8289423696, 0), (8289423695, 8289423696, 1), (8289423695, 8289423694, 0), (8289423695, 8289423694, 1), (8289423696, 8289423697, 0), (8289423696, 8289423697, 1), (8289423696, 8289423695, 0), (8289423696, 8289423695, 1), (8289423697, 8289423698, 0), (8289423697, 8289423698, 1), (8289423697, 8289423696, 0), (8289423697, 8289423696, 1), (8289423698, 8289423699, 0), (8289423698, 8289423699, 1), (8289423698, 8289423697, 0), (8289423698, 8289423697, 1), (8289423699, 8289423700, 0), (8289423699, 8289423700, 1), (8289423699, 8289423698, 0), (8289423699, 8289423698, 1), (8289423700, 8289423701, 0), (8289423700, 8289423701, 1), (8289423700, 8289423699, 0), (8289423700, 8289423699, 1), (8289423701, 8289423702, 0), (8289423701, 8289423702, 1), (8289423701, 8289423700, 0), (8289423701, 8289423700, 1), (8289423702, 8289423703, 0), (8289423702, 8289423703, 1), (8289423702, 8289423701, 0), (8289423702, 8289423701, 1), (8289423703, 8289423704, 0), (8289423703, 8289423704, 1), (8289423703, 8289423702, 0), (8289423703, 8289423702, 1), (8289423704, 9594032173, 0), (8289423704, 9594032173, 1), (8289423704, 8289423703, 0), (8289423704, 8289423703, 1), (8289423704, 8289423705, 0), (8289423704, 8289423705, 1), (8289423705, 8289423704, 0), (8289423705, 8289423704, 1), (8289423705, 8289423706, 0), (8289423705, 8289423706, 1), (8289423706, 8289423705, 0), (8289423706, 8289423705, 1), (8289423706, 8289423707, 0), (8289423706, 8289423707, 1), (8289423707, 8289423706, 0), (8289423707, 8289423706, 1), (8289423707, 8289423708, 0), (8289423707, 8289423708, 1), (8289423708, 8289423707, 0), (8289423708, 8289423707, 1), (8289423708, 8289423709, 0), (8289423708, 8289423709, 1), (8289423709, 8289423708, 0), (8289423709, 8289423708, 1), (8289423709, 8289423710, 0), (8289423709, 8289423710, 1), (8289423710, 8289423709, 0), (8289423710, 8289423709, 1), (8289423710, 8289423711, 0), (8289423710, 8289423711, 1), (8289423711, 8289423710, 0), (8289423711, 8289423710, 1), (8289423711, 8289423712, 0), (8289423711, 8289423712, 1), (8289423712, 8289423711, 0), (8289423712, 8289423711, 1), (8289423712, 8289423680, 0), (8289423712, 8289423392, 0), (3600917412, 11840443525, 0), (3600917412, 11840443525, 1), (3600917412, 11840443526, 0), (3600917412, 11840443526, 1), (3739546538, 11840443527, 0), (3739546538, 11840443527, 1), (3739546538, 8289423682, 0), (3739546538, 8289423682, 1)])

In [6]:
G.edges[(8289423392, 9594032161, 0)]

{'osmid': 354355814,
 'landuse': 'residential',
 'oneway': False,
 'reversed': True,
 'length': np.float64(13.212759233698653)}

In [7]:
adj_list = { node : list(G.neighbors(node)) for node in G.nodes()}
adj_list

{8289423392: [9594032161, 8289423680, 8289423712],
 9594032161: [8289423392, 9594032162],
 9594032162: [9594032161, 9594032163],
 9594032163: [9594032162, 9594032164],
 9594032164: [9594032163, 9594032165],
 9594032165: [9594032164, 9594032166],
 9594032166: [9594032165, 9594032167],
 9594032167: [9594032166, 9594032168],
 9594032168: [9594032167, 9594032169],
 9594032169: [9594032168, 9594032170],
 9594032170: [9594032169, 9594032171],
 9594032173: [9594032172, 8289423704],
 9594032172: [9594032171, 9594032173],
 9594032171: [9594032170, 9594032172],
 11840443527: [11840443526, 3739546538],
 11840443526: [3600917412, 11840443527],
 11840443525: [8289423686, 3600917412],
 9598794475: [8289423690, 8289423689],
 8289423680: [8289423681, 8289423392, 8289423712],
 8289423681: [8289423682, 8289423680],
 8289423682: [3739546538, 8289423681],
 8289423686: [8289423687, 11840443525],
 8289423687: [8289423688, 8289423686],
 8289423688: [8289423689, 8289423687],
 8289423689: [9598794475, 8289423688],
 8289423690: [8289423691, 9598794475],
 8289423691: [8289423694, 8289423690],
 8289423694: [8289423695, 8289423691],
 8289423695: [8289423696, 8289423694],
 8289423696: [8289423697, 8289423695],
 8289423697: [8289423698, 8289423696],
 8289423698: [8289423699, 8289423697],
 8289423699: [8289423700, 8289423698],
 8289423700: [8289423701, 8289423699],
 8289423701: [8289423702, 8289423700],
 8289423702: [8289423703, 8289423701],
 8289423703: [8289423704, 8289423702],
 8289423704: [9594032173, 8289423703, 8289423705],
 8289423705: [8289423704, 8289423706],
 8289423706: [8289423705, 8289423707],
 8289423707: [8289423706, 8289423708],
 8289423708: [8289423707, 8289423709],
 8289423709: [8289423708, 8289423710],
 8289423710: [8289423709, 8289423711],
 8289423711: [8289423710, 8289423712],
 8289423712: [8289423711, 8289423680, 8289423392],
 3600917412: [11840443525, 11840443526],
 3739546538: [11840443527, 8289423682]}

In [8]:
nodes,edges = ox.graph_to_gdfs(G)

In [9]:
nodes

                     y          x                   geometry
osmid
8289423392   28.223565  83.674372  POINT (83.67437 28.22356)
9594032161   28.223484  83.674471  POINT (83.67447 28.22348)
9594032162   28.223407  83.674579  POINT (83.67458 28.22341)
9594032163   28.223295  83.674670   POINT (83.67467 28.2233)
9594032164   28.223211  83.674713  POINT (83.67471 28.22321)
9594032165   28.223146  83.674792  POINT (83.67479 28.22315)
9594032166   28.223056  83.674841  POINT (83.67484 28.22306)
9594032167   28.222846  83.674855  POINT (83.67485 28.22285)
9594032168   28.222589  83.674992  POINT (83.67499 28.22259)
9594032169   28.222492  83.675037  POINT (83.67504 28.22249)
9594032170   28.222234  83.675104   POINT (83.6751 28.22223)
9594032173   28.221442  83.675783  POINT (83.67578 28.22144)
9594032172   28.221674  83.675399   POINT (83.6754 28.22167)
9594032171   28.221898  83.675196    POINT (83.6752 28.2219)
11840443527  28.216169  83.677588  POINT (83.67759 28.21617)
11840443526  28.216430  83.677669  POINT (83.67767 28.21643)
11840443525  28.216753  83.677762  POINT (83.67776 28.21675)
9598794475   28.218498  83.676794   POINT (83.67679 28.2185)
8289423680   28.212497  83.675598    POINT (83.6756 28.2125)
8289423681   28.212657  83.675791  POINT (83.67579 28.21266)
8289423682   28.214775  83.677196   POINT (83.6772 28.21478)
8289423686   28.216956  83.677744  POINT (83.67774 28.21696)
8289423687   28.217233  83.677580  POINT (83.67758 28.21723)
8289423688   28.217557  83.677387  POINT (83.67739 28.21756)
8289423689   28.218065  83.677175  POINT (83.67718 28.21806)
8289423690   28.218859  83.676472  POINT (83.67647 28.21886)
8289423691   28.218918  83.676401   POINT (83.6764 28.21892)
8289423694   28.219251  83.676105   POINT (83.6761 28.21925)
8289423695   28.219405  83.676046   POINT (83.67605 28.2194)
8289423696   28.219552  83.676032  POINT (83.67603 28.21955)
8289423697   28.219663  83.675995  POINT (83.67599 28.21966)
8289423698   28.219776  83.676006  POINT (83.67601 28.21978)
8289423699   28.220457  83.675995  POINT (83.67599 28.22046)
8289423700   28.220589  83.675845  POINT (83.67584 28.22059)
8289423701   28.220703  83.675834   POINT (83.67583 28.2207)
8289423702   28.220901  83.675920   POINT (83.67592 28.2209)
8289423703   28.221014  83.675920  POINT (83.67592 28.22101)
8289423704   28.221128  83.675898   POINT (83.6759 28.22113)
8289423705   28.221204  83.675813   POINT (83.67581 28.2212)
8289423706   28.221222  83.675684  POINT (83.67568 28.22122)
8289423707   28.221090  83.675501   POINT (83.6755 28.22109)
8289423708   28.220844  83.675244  POINT (83.67524 28.22084)
8289423709   28.220438  83.675018  POINT (83.67502 28.22044)
8289423710   28.220305  83.674815  POINT (83.67481 28.22031)
8289423711   28.220211  83.674740  POINT (83.67474 28.22021)
8289423712   28.219965  83.674643  POINT (83.67464 28.21997)
3600917412   28.216633  83.677782  POINT (83.67778 28.21663)
3739546538   28.215602  83.677434   POINT (83.67743 28.2156)

In [10]:
edges

                                 osmid      landuse  oneway  reversed  \
u          v           key
8289423392 9594032161  0     354355814  residential   False      True
                       1    1042191598          NaN   False      True
           8289423680  0     354355814  residential   False     False
           8289423712  0    1042191598          NaN   False     False
9594032161 8289423392  0     354355814  residential   False     False
...                                ...          ...     ...       ...
3600917412 11840443526 1     891877574          NaN   False     False
3739546538 11840443527 0     354355814  residential   False     False
                       1     891877574          NaN   False      True
           8289423682  0     354355814  residential   False      True
                       1     891877574          NaN   False     False

                                 length  \
u          v           key
8289423392 9594032161  0      13.212759
                       1      13.212759
           8289423680  0    3150.328694
           8289423712  0     544.575157
9594032161 8289423392  0      13.212759
...                                 ...
3600917412 11840443526 1      25.190349
3739546538 11840443527 0      64.880515
                       1      64.880515
           8289423682  0      94.860673
                       1      94.860673

                                                                     geometry
u          v           key
8289423392 9594032161  0    LINESTRING (83.67437 28.22356, 83.67447 28.22348)
                       1    LINESTRING (83.67437 28.22356, 83.67447 28.22348)
           8289423680  0    LINESTRING (83.67437 28.22356, 83.6743 28.2236...
           8289423712  0    LINESTRING (83.67437 28.22356, 83.67437 28.223...
9594032161 8289423392  0    LINESTRING (83.67447 28.22348, 83.67437 28.22356)
...                                                                       ...
3600917412 11840443526 1    LINESTRING (83.67778 28.21663, 83.67767 28.21643)
3739546538 11840443527 0     LINESTRING (83.67743 28.2156, 83.67759 28.21617)
                       1     LINESTRING (83.67743 28.2156, 83.67759 28.21617)
           8289423682  0      LINESTRING (83.67743 28.2156, 83.6772 28.21478)
                       1      LINESTRING (83.67743 28.2156, 83.6772 28.21478)

[194 rows x 6 columns]

In [11]:
import folium
center =[nodes.geometry.y.mean(), nodes.geometry.x.mean()]
m = folium.Map(location =center , zoom_start = 16 , tiles = "OpenStreetMap")
m

In [12]:
# Map Layer
all_edges = folium.FeatureGroup(name = "All edges " , show = True)
for _,row in edges.iterrows():
    coords = [(lat ,lon) for lon ,lat in row.geometry.coords]
    text = row.get("length")

    folium.PolyLine(
    coords,
    popup = text ,
    color = "red",
    weight = 2 ,
    opacity = 0.8
    ).add_to(all_edges)
    
all_edges.add_to(m)
m

In [13]:
#Add Nodes 
node_layer = folium.FeatureGroup(name = " All nodes ")
for node , data in nodes.iterrows():
    lat = data.geometry.y
    lon = data.geometry.x

    folium.CircleMarker(
        location = [lat,lon],
        radius = 1 ,
        color = "blue",
        fill = True ,
        fill_color = "yellow",
        fill_opacity = 0.5 ,
        popup = str(node)
    ).add_to(node_layer)
node_layer.add_to(m)
m

In [14]:
start_node =8289423681
goal_node = 8289423712
folium.CircleMarker(
    location = [G.nodes[start_node]["y"], G.nodes[start_node]["x"]],
    radius = 7,
    color = "green",
    fill = True, fill_color = "green", fill_opacity = 0.6, popup = "Start"
).add_to(node_layer)
folium.CircleMarker(
    location = [G.nodes[goal_node]["y"], G.nodes[goal_node]["x"]],
    radius = 7,
    color = "green",
    fill = True, fill_color = "green", fill_opacity = 0.6, popup = "GOal"
).add_to(node_layer)

m

## BFS Algorithm

In [15]:

from collections import deque
def bfs(graph, start_node, goal_node):
    queue = deque([start_node])
    parents = {start_node: None}
    visited_order = []
    step_trace = []

    while queue:
        current = queue.popleft()
        visited_order.append(current)

        discovered_now = []
        if current != goal_node:
            for neighbor in graph[current]:
                if neighbor not in parents:
                    parents[neighbor] = current
                    queue.append(neighbor)
                    discovered_now.append(neighbor)

        step_trace.append({
            "current": current,
            "visited": list(visited_order),
            "queue": list(queue),
            "discovered": discovered_now
        })

        if current == goal_node:
            break

    if goal_node not in parents:
        return step_trace, None

    path = []
    current = goal_node
    while current is not None:
        path.append(current)
        current = parents[current]
    path.reverse()
    return step_trace, path



tr, p = bfs(adj_list, start_node, goal_node)
tr

[{'current': 8289423681,
  'visited': [8289423681],
  'queue': [8289423682, 8289423680],
  'discovered': [8289423682, 8289423680]},
 {'current': 8289423682,
  'visited': [8289423681, 8289423682],
  'queue': [8289423680, 3739546538],
  'discovered': [3739546538]},
 {'current': 8289423680,
  'visited': [8289423681, 8289423682, 8289423680],
  'queue': [3739546538, 8289423392, 8289423712],
  'discovered': [8289423392, 8289423712]},
 {'current': 3739546538,
  'visited': [8289423681, 8289423682, 8289423680, 3739546538],
  'queue': [8289423392, 8289423712, 11840443527],
  'discovered': [11840443527]},
 {'current': 8289423392,
  'visited': [8289423681, 8289423682, 8289423680, 3739546538, 8289423392],
  'queue': [8289423712, 11840443527, 9594032161],
  'discovered': [9594032161]},
 {'current': 8289423712,
  'visited': [8289423681,
   8289423682,
   8289423680,
   3739546538,
   8289423392,
   8289423712],
  'queue': [11840443527, 9594032161],
  'discovered': []}]

In [16]:
path_edge_layer = folium.FeatureGroup(name="Path Edge", show=True)

path_edges = []

for u in p:
    for v in G.neighbors(u):
        if v in p:
            path_edges.append((u, v))

path_edges_data = []

for u, v in path_edges:
    data = G.get_edge_data(u, v)
    if data:
        for key, attrs in data.items():
            path_edges_data.append((u, v, attrs))

for u, v, attrs in path_edges_data:
    geom = attrs.get("geometry")
    if geom:
        coords = [(lat, lon) for lon, lat in geom.coords]
    else:
        coords = [
            (G.nodes[u]['y'], G.nodes[u]['x']),
            (G.nodes[v]['y'], G.nodes[v]['x'])
        ]
    folium.PolyLine(
        coords,
        color="green",
        weight=5,
        opacity=0.5
    ).add_to(path_edge_layer)

path_edge_layer.add_to(m)
m

In [17]:
found_node = folium.FeatureGroup(name="Found Node", show=True)

for node in p:
    x, y = G.nodes[node].values()
    folium.CircleMarker(
        location=[G.nodes[node]["y"], G.nodes[node]["x"]],
        radius=4,
        color="green",
        fill=True,
        fill_color="green",
        fill_opacity=0.2,
        popup=str(node)
    ).add_to(found_node)

found_node.add_to(m)
m

In [18]:
# Visited Data

visited = tr[-1:][0]["visited"]
visit_edge_layer = folium.FeatureGroup(name="Visit Edge", show=True)

visit_edges = []

for u in visited:
    for v in G.neighbors(u):
        if v in visited:
            visit_edges.append((u, v))

visit_edges_data = []

for u, v in visit_edges:
    data = G.get_edge_data(u, v)
    if data:
        for key, attrs in data.items():
            visit_edges_data.append((u, v, attrs))

for u, v, attrs in visit_edges_data:
    geom = attrs.get("geometry")
    if geom:
        coords = [(lat, lon) for lon, lat in geom.coords]
    else:
        coords = [
            (G.nodes[u]['y'], G.nodes[u]['x']),
            (G.nodes[v]['y'], G.nodes[v]['x'])
        ]
    folium.PolyLine(
        coords,
        color="yellow",
        weight=5,
        opacity=0.5
    ).add_to(visit_edge_layer)

visit_edge_layer.add_to(m)
m

## DFS Algorithm

In [19]:
def dfs(graph, start_node, goal_node):
    stack = [start_node]
    parents = {start_node: None}
    visited = set()
    
    visited_order = []
    step_trace = []

    while stack:
        current = stack.pop()

        if current in visited:
            continue

        visited.add(current)
        visited_order.append(current)

        discovered_now = []

        if current == goal_node:
            step_trace.append({
                "current": current,
                "visited": list(visited_order),
                "stack": list(stack),
                "discovered": discovered_now
            })
            break

        for neighbor in graph[current]:
            if neighbor not in visited and neighbor not in parents:
                parents[neighbor] = current
                stack.append(neighbor)
                discovered_now.append(neighbor)

        step_trace.append({
            "current": current,
            "visited": list(visited_order),
            "stack": list(stack),
            "discovered": discovered_now
        })

    # reconstruct path
    if goal_node not in parents:
        return step_trace, None

    path = []
    cur = goal_node
    while cur is not None:
        path.append(cur)
        cur = parents[cur]

    path.reverse()
    return step_trace, path

In [20]:
dfs_trace, dfs_path = dfs(adj_list, start_node, goal_node)

print("DFS Path Length:", len(dfs_path) if dfs_path else "Not Found")
print("DFS Path:", dfs_path)

DFS Path Length: 3
DFS Path: [8289423681, 8289423680, 8289423712]

In [21]:
dfs_layer = folium.FeatureGroup(name="DFS Path", show=True)

for i in range(len(dfs_path) - 1):
    u = dfs_path[i]
    v = dfs_path[i + 1]

    data = G.get_edge_data(u, v)
    if data:
        for key, attrs in data.items():
            geom = attrs.get("geometry")

            if geom:
                coords = [(lat, lon) for lon, lat in geom.coords]
            else:
                coords = [
                    (G.nodes[u]['y'], G.nodes[u]['x']),
                    (G.nodes[v]['y'], G.nodes[v]['x'])
                ]

            folium.PolyLine(coords, color="purple", weight=4).add_to(dfs_layer)

dfs_layer.add_to(m)
m

## A* Algorithm

In [22]:
import math

def heuristic(n1, n2):
    x1, y1 = G.nodes[n1]['x'], G.nodes[n1]['y']
    x2, y2 = G.nodes[n2]['x'], G.nodes[n2]['y']

    # simple Euclidean approximation (fast)
    return math.sqrt((x1 - x2)**2 + (y1 - y2)**2)

In [23]:
import heapq

def a_star(graph, start_node, goal_node):
    open_set = []
    heapq.heappush(open_set, (0, start_node))

    parents = {start_node: None}
    g_cost = {start_node: 0}

    visited_order = []
    step_trace = []

    while open_set:
        _, current = heapq.heappop(open_set)

        visited_order.append(current)

        if current == goal_node:
            break

        discovered_now = []

        for neighbor in graph[current]:
            edge_weight = 1  # or use real distance if available

            tentative_g = g_cost[current] + edge_weight

            if neighbor not in g_cost or tentative_g < g_cost[neighbor]:
                g_cost[neighbor] = tentative_g
                f_cost = tentative_g + heuristic(neighbor, goal_node)

                heapq.heappush(open_set, (f_cost, neighbor))
                parents[neighbor] = current
                discovered_now.append(neighbor)

        step_trace.append({
            "current": current,
            "visited": list(visited_order),
            "open_set": [n[1] for n in open_set],
            "discovered": discovered_now
        })

    if goal_node not in parents:
        return step_trace, None

    path = []
    cur = goal_node
    while cur is not None:
        path.append(cur)
        cur = parents[cur]

    path.reverse()
    return step_trace, path

In [24]:
astar_trace, astar_path = a_star(adj_list, start_node, goal_node)

print("A* Path Length:", len(astar_path) if astar_path else "Not Found")
print("A* Path:", astar_path)

A* Path Length: 3
A* Path: [8289423681, 8289423680, 8289423712]

In [25]:
astar_layer = folium.FeatureGroup(name="A* Path", show=True)

for i in range(len(astar_path) - 1):
    u = astar_path[i]
    v = astar_path[i + 1]

    data = G.get_edge_data(u, v)
    if data:
        for key, attrs in data.items():
            geom = attrs.get("geometry")

            if geom:
                coords = [(lat, lon) for lon, lat in geom.coords]
            else:
                coords = [
                    (G.nodes[u]['y'], G.nodes[u]['x']),
                    (G.nodes[v]['y'], G.nodes[v]['x'])
                ]

            folium.PolyLine(coords, color="orange", weight=5).add_to(astar_layer)

astar_layer.add_to(m)
m

## GBS Algorithm

In [26]:
import heapq

In [27]:
def greedy_best_first_search(graph, start_node, goal_node):
    open_set = []
    
    # ONLY heuristic used (no g_cost like A*)
    heapq.heappush(open_set, (heuristic(start_node, goal_node), start_node))

    parents = {start_node: None}
    visited = set()

    visited_order = []
    step_trace = []

    while open_set:
        _, current = heapq.heappop(open_set)

        if current in visited:
            continue

        visited.add(current)
        visited_order.append(current)

        if current == goal_node:
            break

        discovered_now = []

        for neighbor in graph[current]:
            if neighbor not in visited:
                heapq.heappush(open_set, (heuristic(neighbor, goal_node), neighbor))

                if neighbor not in parents:
                    parents[neighbor] = current
                    discovered_now.append(neighbor)

        step_trace.append({
            "current": current,
            "visited": list(visited_order),
            "open_set": [n[1] for n in open_set],
            "discovered": discovered_now
        })

    if goal_node not in parents:
        return step_trace, None

    # Reconstruct path
    path = []
    cur = goal_node
    while cur is not None:
        path.append(cur)
        cur = parents[cur]

    path.reverse()
    return step_trace, path

In [28]:
gbs_trace, gbs_path = greedy_best_first_search(adj_list, start_node, goal_node)

print("GBS Path Length:", len(gbs_path) if gbs_path else "Not Found")
print("GBS Path:", gbs_path)

GBS Path Length: 33
GBS Path: [8289423681, 8289423682, 3739546538, 11840443527, 11840443526, 3600917412, 11840443525, 8289423686, 8289423687, 8289423688, 8289423689, 9598794475, 8289423690, 8289423691, 8289423694, 8289423695, 8289423696, 8289423697, 8289423698, 8289423699, 8289423700, 8289423701, 8289423702, 8289423703, 8289423704, 8289423705, 8289423706, 8289423707, 8289423708, 8289423709, 8289423710, 8289423711, 8289423712]

In [29]:
gbs_layer = folium.FeatureGroup(name="GBS Path", show=True)

for i in range(len(gbs_path) - 1):
    u = gbs_path[i]
    v = gbs_path[i + 1]

    data = G.get_edge_data(u, v)
    if data:
        for key, attrs in data.items():
            geom = attrs.get("geometry")

            if geom:
                coords = [(lat, lon) for lon, lat in geom.coords]
            else:
                coords = [
                    (G.nodes[u]['y'], G.nodes[u]['x']),
                    (G.nodes[v]['y'], G.nodes[v]['x'])
                ]

            folium.PolyLine(coords, color="blue", weight=5).add_to(gbs_layer)

gbs_layer.add_to(m)
m